---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: check-golangci
  commands:
  - make check-golangci
- name: build-docker-image
  commands:
  - make docker IMAGE_TAG=test
- name: restart service
  commands:
  - docker compose -f .docker-compose/test.yaml down
  - docker compose -f .docker-compose/test.yaml up -d
  - docker image prune -f

trigger:
  branch:
  - main
  event:
  - push
...