service: notification

api:
  port: 9080
  debug: true


log:
  level: debug
  target: os

mail:
  provider: aws

aws:
  ses:
    from: "\"OOSA Group\" <developer@arwork.tw>"
    region: ap-northeast-1
    credentails:
      filename: ./.aws/credentials
      profile: default

identity:
  url: http://localhost:4434