networks:
  oosa-network:
    external: true
    name: network.oosa

name: oosa-api-service
services:
  oosa_notify:
    container_name: oosa_notify
    image: arwoosa/notifaction:test
    restart: always
    volumes: 
      - $HOME/goproject/arwoosa/secrets/.aws:/etc/aws
    environment:
      - AWS_SES_CREDENTIALS_FILENAME=/etc/aws/credentials
      - AWS_SES_FROM="\"OOSA Test Group\" <developer@arwork.tw>"
      - IDENTITY_URL=http://kratos:4434/admin/identities
    networks:
    - oosa-network